// Single source for iconography. Everything uses Lucide at a consistent
// stroke so the product reads as one coherent set (no emoji anywhere).
import {
  LayoutDashboard,
  Briefcase,
  Hexagon,
  Clock3,
  Sparkles,
  Flame,
  CalendarDays,
  Plus,
  X,
  Trash2,
  Check,
  GripVertical,
  Target,
  ListTodo,
  Repeat2,
  CornerDownLeft,
  ArrowRight,
  ArrowLeft,
  ExternalLink,
  PartyPopper,
  CheckCircle2,
  FolderKanban,
  FileText,
  Flag,
  Link2,
  Pencil,
  CalendarRange,
  Wallet,
  PiggyBank,
  LayoutTemplate,
  ChevronLeft,
  ChevronRight,
  Sun,
  Moon,
  Users,
  Phone,
  Mail,
  Repeat,
  Search,
  SlidersHorizontal,
  Landmark,
  CreditCard,
  Banknote,
  Send,
  Bitcoin,
  Zap,
  Receipt,
  Paperclip,
  Upload,
  TrendingUp,
  TrendingDown,
  type LucideIcon,
} from "lucide-react";

export type { LucideIcon };

export const Icons = {
  overview: LayoutDashboard,
  calendar2: CalendarRange,
  jobs: Briefcase,
  sidework: Hexagon,
  projects: FolderKanban,
  income: Wallet,
  budget: PiggyBank,
  template: LayoutTemplate,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  sun: Sun,
  moon: Moon,
  clients: Users,
  phone: Phone,
  mail: Mail,
  partTime: Clock3,
  personal: Sparkles,
  flame: Flame,
  calendar: CalendarDays,
  plus: Plus,
  close: X,
  trash: Trash2,
  check: Check,
  grip: GripVertical,
  target: Target,
  todo: ListTodo,
  habit: Repeat2,
  enter: CornerDownLeft,
  arrow: ArrowRight,
  back: ArrowLeft,
  link: ExternalLink,
  docLink: Link2,
  doc: FileText,
  milestone: Flag,
  edit: Pencil,
  celebrate: PartyPopper,
  done: CheckCircle2,
  recurring: Repeat,
  search: Search,
  filter: SlidersHorizontal,
  bank: Landmark,
  card: CreditCard,
  wallet: Banknote,
  send: Send,
  coins: Bitcoin,
  bolt: Zap,
  finance: Wallet,
  expense: Receipt,
  attach: Paperclip,
  upload: Upload,
  trendUp: TrendingUp,
  trendDown: TrendingDown,
} as const;

// Module → icon, so nav, overview, and quick-add stay in sync.
export const MODULE_ICON = {
  jobs: Icons.jobs,
  sidework: Icons.sidework,
  projects: Icons.projects,
  "part-time": Icons.partTime,
  personal: Icons.personal,
} as const;
